### PR TITLE
Fix env format in Dockerfile

### LINKED ISSUE #233: [BUG]: `docker build --check` complains about legacy ENV format
### Issue Description

Running `docker build --check` produces this warning:

```
WARNING: LegacyKeyValueFormat - https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
"ENV key=value" should be used instead of legacy "ENV key value" format
Dockerfile:214
--------------------
 212 |     
 213 |     # Env vars for the nvidia-container-runtime.
 214 | >>> ENV NVIDIA_VISIBLE_DEVICES all
 215 |     ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
 216 |     ENV QT_X11_NO_MITSHM 1
--------------------

WARNING: LegacyKeyValueFormat - https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
"ENV key=value" should be used instead of legacy "ENV key value" format
Dockerfile:215
--------------------
 213 |     # Env vars for the nvidia-container-runtime.
 214 |     ENV NVIDIA_VISIBLE_DEVICES all
 215 | >>> ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
 216 |     ENV QT_X11_NO_MITSHM 1
 217 |     
--------------------

WARNING: LegacyKeyValueFormat - https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/
"ENV key=value" should be used instead of legacy "ENV key value" format
Dockerfile:216
--------------------
 214 |     ENV NVIDIA_VISIBLE_DEVICES all
 215 |     ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
 216 | >>> ENV QT_X11_NO_MITSHM 1
 217 |     
--------------------
```

### Steps to Reproduce

```
cd .docker && docker build --check .
```

### Expected Behavior

No warnings

### Error Message

```bash
see above
```

### Runtime Environment

Ubuntu 20.04 on amd64 running Docker version 27.1.1, build 6312585

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by amarburg**
## Changes Made

Fixes three ENVs into the preferred "key=value" format.

## Associated Issues

- Fixes #233 

## Testing

`docker build --check .` produces:

```
ci

Check complete, no warnings found.

desktop

Check complete, no warnings found.

desktop-nvidia

Check complete, no warnings found.

robot

Check complete, no warnings found.
```

### CODE REVIEW

**Review by evan-palmer — APPROVED** [review]

**Comment by evan-palmer** [comment]
Going to wait for #220 before I merge this one

**Comment by evan-palmer** [comment]
This should be good to merge once the CI is done

**Comment by evan-palmer** [comment]
Looks like it needs a rebase first

**Comment by amarburg** [comment]
> Looks like it needs a rebase first

Rebased, waiting for CI ...

**Comment by evan-palmer** [comment]
@mergify backport jazzy iron humble

**Pull request merged**
