### PR TITLE
Initial patch for enabling GUIDED mode and mission planning

### LINKED ISSUE #63: [BUG] ArduSub rejects request to switch into GUIDED mode
Per @ssicari: After further investigating the use of QGroundControl (QGC), QGC recognizes the motors being armed and disarmed. It is not currently depicting the location of the vehicle, and when I try to run a basic way point mission it fails because it can not enter `GUIDED` mode. I have tried to manually test if I can put the vehicle into `GUIDED` mode via the ROS CLI but can not get it to recognize the command. Following the MAVROS docs, I can check the current mode it is in and see the possible modes it could change to, but everytime I try to actually change the mode, it says invalid passed service type. I was wondering if you have manually changed modes before and had a working command because the ones directly from the docs don't seem to work along with a few other variations I have tried. Thank you!

_Originally posted by @evan-palmer in https://github.com/evan-palmer/blue/discussions/57_

### PR DESCRIPTION
**Pull request by evan-palmer**
# Checklist

- [x] I have performed a thorough review of my code
- [x] I have sufficiently commented my code
- [x] The implementation follows the project style conventions
- [x] All project unit tests are passing
- [x] If relevant, documentation has been provided or updated to discuss the changes made
- [x] System integration tests were performed successfully

## Changes Made

The ArduSub parameters loaded were modified due to their failure to enable the use of GUIDED mode and mission planning via QGroundControl. Furthermore, the `setpoint_position` and `setpoint_velocity` MAVROS plugins were added to enable sending commands to the vehicle while in GUIDED mode. From this, users can now switch into GUIDED mode to send commands via MAVROS and can also create missions within QGC for the ROV to execute.

 There are a few caveats in this initial patch, however:
1. The vehicle can fly? If you send a really large positive Z-position (above surface), the vehicle will somehow fly there. For those that try this out, ROS/MAVROS uses the conventional ENU frame, so when you send commands using MAVROS, make sure to send commands in the ENU frame.
2. I am still unable to select a location in QGC using the `Go to location` interface. When I try to use that functionality, QGC still indicates that the vehicle does not support GUIDED mode. Nonetheless, I can still set GUIDED mode and arm the vehicle.

## Associated Issues

- Fixes #63 

## Testing

Preliminary testing was done in SITL.

### CODE REVIEW

**Comment by evan-palmer** [comment]
@sscari, I tried this out and was able to get some basic mission planning and GUIDED mode commands to work. The ArduSub version integrated in the project should include @rakeshv24's latest PR into ArduSub which now enables velocity setpoints. I haven't tested that out for confirmation though.

**Comment by evan-palmer** [comment]
> > @ssicari, I tried this out and was able to get some basic mission planning and GUIDED mode commands to work. The ArduSub version integrated in the project should include @rakeshv24's latest PR into ArduSub too which now enables velocity setpoints. I haven't tested that out for confirmation though.
> 
> I pulled the changes and double checked the files have updated, but I still can not get it to work. I run the ros2 launch command with the sim and then I run qgroundcontrol and wait for it to connect. After that I tried to set waypoints but it still failed to change to guided mode, and then I tried to use the drop down menu to change to guided mode but that still didn't work. Is this how you tested it? When you say the preliminary testing was with SITL are you just talking about launching ardusub with the sim? When you talk about the go to interface in qgroundcontrol is that just the interface to set waypoints/have you just been using ROS CLI commands to change it to guided mode? Thank you

Here are the steps that I took to run the updated version (make sure to run `colcon build && source install/setup.bash` from the colcon workspace beforehand--otherwise the configuration files won't be updated):
1. Launched Blue: `ros2 launch blue_bringup bluerov2_heavy.launch.py use_sim:=true` (any of the models should work)
2. Launch QGC--this can also be open before Blue is launched
3. Wait for QGC to establish a connection with the vehicle. When the connection is established, you should now see a yellow circle on the Oregon coast where the vehicle is initialized
4. To switch to GUIDED mode then arm: you could probably do the reverse order, but this is what I ran
5. You should now be able to send commands to the vehicle using MAVROS and the ROS 2 CLI
6. If you want to use the mission planning interface, I started by creating a simple mission with a takeoff setpoint and 3 waypoints each with an altitude of -5.0m, uploaded the plan, then, when prompted to start the mission, started the mission using the slider.

With regards to the preliminary testing, yes, the testing was all done with SITL and Gazebo. I'm not at my desktop at the moment, but I will re-check the integration this evening if these steps don't work for you.

**Comment by ssicari** [comment]
> > > @ssicari, I tried this out and was able to get some basic mission planning and GUIDED mode commands to work. The ArduSub version integrated in the project should include @rakeshv24's latest PR into ArduSub too which now enables velocity setpoints. I haven't tested that out for confirmation though.
> > 
> > 
> > I pulled the changes and double checked the files have updated, but I still can not get it to work. I run the ros2 launch command with the sim and then I run qgroundcontrol and wait for it to connect. After that I tried to set waypoints but it still failed to change to guided mode, and then I tried to use the drop down menu to change to guided mode but that still didn't work. Is this how you tested it? When you say the preliminary testing was with SITL are you just talking about launching ardusub with the sim? When you talk about the go to interface in qgroundcontrol is that just the interface to set waypoints/have you just been using ROS CLI commands to change it to guided mode? Thank you
> 
> Here are the steps that I took to run the updated version (make sure to run `colcon build && source install/setup.bash` from the colcon workspace beforehand--otherwise the configuration files won't be updated):
> 
>     1. Launched Blue: `ros2 launch blue_bringup bluerov2_heavy.launch.py use_sim:=true` (any of the models should work)
> 
>     2. Launch QGC--this can also be open before Blue is launched
> 
>     3. Wait for QGC to establish a connection with the vehicle. When the connection is established, you should now see a yellow circle on the Oregon coast where the vehicle is initialized
> 
>     4. To switch to GUIDED mode then arm: you could probably do the reverse order, but this is what I ran
> 
>     5. You should now be able to send commands to the vehicle using MAVROS and the ROS 2 CLI
> 
>     6. If you want to use the mission planning interface, I started by creating a simple mission with a takeoff setpoint and 3 waypoints each with an altitude of -5.0m, uploaded the plan, then, when prompted to start the mission, started the mission using the slider.
> 
> 
> With regards to the preliminary testing, yes, the testing was all done with SITL and Gazebo. I'm not at my desktop at the moment, but I will re-check the integration this evening if these steps don't work for you.

So after confirming I was on the correct branch and I have the updated files I rebuilt and sourced it. I ran the sim command. After that I launch Qgroundcontrol and wait for it to connect, I will attach a screen shot of what it looks like for me. I have tried using qground control to make a starting take off point followed by two way points of -5.0m and then run it. It says failed to enter guided mode. The ROS CLI and mavproxy commands also says it fails to enter guided mode as well still. As for the SITL what exactly is that in this sense. I know in previous repos we start the sim vehicle of the SITL with the Tools... command. I will keep playing around with it for now and check my qgroundcontrol logs, I have noticed qgroundcontrol loses communication every once in a while maybe there is more to that on my end that is causing these problems. I appreciate the response, no rush! Thank you!

image

**Comment by evan-palmer** [comment]
> As for the SITL what exactly is that in this sense. I know in previous repos we start the sim vehicle of the SITL with the Tools... command

SITL in this case is the ArduSub + Gazebo interface. When you launch with the simulation ArduSub runs SITL instead of trying to establish a connection with a real vehicle. I'll do some more testing with the patch tonight. The screenshot that you provided is what I would expect things to look like too

**Comment by ssicari** [comment]
> > As for the SITL what exactly is that in this sense. I know in previous repos we start the sim vehicle of the SITL with the Tools... command
> 
> SITL in this case is the ArduSub + Gazebo interface. When you launch with the simulation ArduSub runs SITL instead of trying to establish a connection with a real vehicle. I'll do some more testing with the patch tonight. The screenshot that you provided is what I would expect things to look like too

Ah I see. I am attaching some screenshots here to archive them, while I look into them. These are the messages I receive when Qgroundcontrol loses communication. Thanks again for the information and response!


image

image

image

**Comment by ssicari** [comment]
> > As for the SITL what exactly is that in this sense. I know in previous repos we start the sim vehicle of the SITL with the Tools... command
> 
> SITL in this case is the ArduSub + Gazebo interface. When you launch with the simulation ArduSub runs SITL instead of trying to establish a connection with a real vehicle. I'll do some more testing with the patch tonight. The screenshot that you provided is what I would expect things to look like too

I have been playing around with it some more and still can not seem to figure out what is wrong on my end or what the differences are between our set ups. The images I sent are all related to losing connection but I think that is unrelated to not being able to be changed into guided mode.

**Comment by evan-palmer** [comment]
> I have been playing around with it some more and still can not seem to figure out what is wrong on my end or what the differences are between our set ups. The images I sent are all related to losing connection but I think that is unrelated to not being able to be changed into guided mode.

I apologize for the late response; I have been/will be away for the next few weeks finishing up some field experiments, so I probably won't be able to get this merged and debugged until those are finished. Here are some comments and debugging steps that you could try in the meantime:
1. I haven't seen the QGC disconnect error in SITL before; although, I have been seeing that on hardware. I was under the impression that it was because of a potential issue with running BlueOS on arm64 (unstable), but it could also be an issue with the latest version of ArduPilot.
2. The main place that I would look is the localization information being sent to the ArduPilot EKF. Each of the interfaces is being used correctly which indicates to me that the position information that is being sent is getting rejected by ArduPilot for some reason. You could try adjusting the weighting of the EKF to favor the position estimation, try playing around with the EK3 parameters, or look into the pose localization information sent to the EKF (from the Gazebo Localizer). You could also try slowing down/speeding up the Gazebo localizer.
3. If you haven't already, it may be worth trying a fresh clone
4. I am using QGC v.4.2.8, but I don't think that is causing the problem

**Comment by evan-palmer** [comment]
> That's fine, I will look into that and possible do a fresh clone. I do not know if you have access to see what version of ardusub you are running? I noticed I am running 4.2 -dev and wondering if the dev branch is unstable and introducing conflicts? Good luck with the field experiments!

You are right; it's certainly possible that there is a conflict with ArduSub. I believe that `*-dev` releases are actually just the ArduPilot `master` branch. I develop in the devcontainer, so I pull the latest version of that each time that I build the image (once every other day or so).

Would you be willing to copy all of the log messages in the terminal to a file and share that (I mostly need to look at the Gazebo + ArduSub outputs)? I will look through that to see if there are any differences there.

**Comment by ssicari** [comment]
> > That's fine, I will look into that and possible do a fresh clone. I do not know if you have access to see what version of ardusub you are running? I noticed I am running 4.2 -dev and wondering if the dev branch is unstable and introducing conflicts? Good luck with the field experiments!
> 
> You are right; it's certainly possible that there is a conflict with ArduSub. I believe that `*-dev` releases are actually just the ArduPilot `master` branch. I develop in the devcontainer, so I pull the latest version of that each time that I build the image (once every other day or so).
> 
> Would you be willing to copy all of the log messages in the terminal to a file and share that (I mostly need to look at the Gazebo + ArduSub outputs)? I will look through that to see if there are any differences there.

Hello, if the *-dev branch works for you I don't think that is the problem then but I still believe it is ardusub related. I copied over the terminal for the sim which I believe should include information on gazebo and ardusub. I am attaching a file too that has the qgroundcontrol terminal if you are curious. If you need any other logs just let me know, thank you!



> > That's fine, I will look into that and possible do a fresh clone. I do not know if you have access to see what version of ardusub you are running? I noticed I am running 4.2 -dev and wondering if the dev branch is unstable and introducing conflicts? Good luck with the field experiments!
> 
> You are right; it's certainly possible that there is a conflict with ArduSub. I believe that `*-dev` releases are actually just the ArduPilot `master` branch. I develop in the devcontainer, so I pull the latest version of that each time that I build the image (once every other day or so).
> 
> Would you be willing to copy all of the log messages in the terminal to a file and share that (I mostly need to look at the Gazebo + ArduSub outputs)? I will look through that to see if there are any differences there.

Hello, if the *-dev branch works for you I don't think that is the problem then but I still believe it is ardusub related. I copied over the terminal for the sim which I believe should include information on gazebo and ardusub. I am attaching a file too that has the qgroundcontrol terminal if you are curious. If you need any other logs just let me know, thank you!



[Gazebo_ArduSub.txt](https://github.com/eva
[Qgroundcontrol.txt](https://github.com/evan-palmer/blue/files/12305486/Qgroundcontrol.txt)
n-palmer/blue/files/12305484/Gazebo_ArduSub.txt)

**Comment by ssicari** [comment]
> > > That's fine, I will look into that and possible do a fresh clone. I do not know if you have access to see what version of ardusub you are running? I noticed I am running 4.2 -dev and wondering if the dev branch is unstable and introducing conflicts? Good luck with the field experiments!
> > 
> > 
> > You are right; it's certainly possible that there is a conflict with ArduSub. I believe that `*-dev` releases are actually just the ArduPilot `master` branch. I develop in the devcontainer, so I pull the latest version of that each time that I build the image (once every other day or so).
> > Would you be willing to copy all of the log messages in the terminal to a file and share that (I mostly need to look at the Gazebo + ArduSub outputs)? I will look through that to see if there are any differences there.
> 
> Hello, if the *-dev branch works for you I don't think that is the problem then but I still believe it is ardusub related. I have noticed that there are alot of plugins being ignored with mavros and I am not sure if they are supposed to be ignored or not. I copied over the terminal for the sim which I believe should include information on gazebo and ardusub. I am attaching a file too that has the qgroundcontrol terminal if you are curious. I tried to to set a flight plan so the bottom of the log files show the error messages when it fails to switch to guided mode. If you need any other logs just let me know, thank you! [Qgroundcontrol.txt](https://github.com/evan-palmer/blue/files/12305496/Qgroundcontrol.txt) [Gazebo_ArduSub.txt](https://github.com/evan-palmer/blue/files/12305498/Gazebo_ArduSub.txt)

I found this screenshot on an article about ardupilot: 
image
and the problem was he was trying to change modes before the IMU was using GPS.

However when looking at my terminal the IMU sets origin but not to the GPS: 
image



> > > That's fine, I will look into that and possible do a fresh clone. I do not know if you have access to see what version of ardusub you are running? I noticed I am running 4.2 -dev and wondering if the dev branch is unstable and introducing conflicts? Good luck with the field experiments!
> > 
> > 
> > You are right; it's certainly possible that there is a conflict with ArduSub. I believe that `*-dev` releases are actually just the ArduPilot `master` branch. I develop in the devcontainer, so I pull the latest version of that each time that I build the image (once every other day or so).
> > Would you be willing to copy all of the log messages in the terminal to a file and share that (I mostly need to look at the Gazebo + ArduSub outputs)? I will look through that to see if there are any differences there.
> 
> Hello, if the *-dev branch works for you I don't think that is the problem then but I still believe it is ardusub related. I have noticed that there are alot of plugins being ignored with mavros and I am not sure if they are supposed to be ignored or not. I copied over the terminal for the sim which I believe should include information on gazebo and ardusub. I am attaching a file too that has the qgroundcontrol terminal if you are curious. I tried to to set a flight plan so the bottom of the log files show the error messages when it fails to switch to guided mode. If you need any other logs just let me know, thank you! [Qgroundcontrol.txt](https://github.com/evan-palmer/blue/files/12305496/Qgroundcontrol.txt) [Gazebo_ArduSub.txt](https://github.com/evan-palmer/blue/files/12305498/Gazebo_ArduSub.txt)

Quick question I am going to add here. What is the gazebo localizer and where is it located? I am assuming it localizes the model in the gazebo sim and sends that data back to ardusub but I am having trouble finding it

> > > That's fine, I will look into that and possible do a fresh clone. I do not know if you have access to see what version of ardusub you are running? I noticed I am running 4.2 -dev and wondering if the dev branch is unstable and introducing conflicts? Good luck with the field experiments!
> > 
> > 
> > You are right; it's certainly possible that there is a conflict with ArduSub. I believe that `*-dev` releases are actually just the ArduPilot `master` branch. I develop in the devcontainer, so I pull the latest version of that each time that I build the image (once every other day or so).
> > Would you be willing to copy all of the log messages in the terminal to a file and share that (I mostly need to look at the Gazebo + ArduSub outputs)? I will look through that to see if there are any differences there.
> 
> Hello, if the *-dev branch works for you I don't think that is the problem then but I still believe it is ardusub related. I have noticed that there are alot of plugins being ignored with mavros and I am not sure if they are supposed to be ignored or not. I copied over the terminal for the sim which I believe should include information on gazebo and ardusub. I am attaching a file too that has the qgroundcontrol terminal if you are curious. I tried to to set a flight plan so the bottom of the log files show the error messages when it fails to switch to guided mode. If you need any other logs just let me know, thank you! [Qgroundcontrol.txt](https://github.com/evan-palmer/blue/files/12305496/Qgroundcontrol.txt) [Gazebo_ArduSub.txt](https://github.com/evan-palmer/blue/files/12305498/Gazebo_ArduSub.txt)

from the Gazebo Localizer). You could also try slowing down/speeding up the Gazebo localizer.

I see the ROS2 node gazebo localizer and where you create it in the localization.launch.py file, but I have a few questions. 1.) I am struggling to find where the code is that could speed up or slow down the localizer, I am only able to find where we create the node and nothing else. Also the ROS2 node gazebo_localizer appears when I leave the localization source as default which is stated to be "mocap". My understanding is that if I leave it to default it will use mocap and should create a node called qualisys localizer instead of gazebo, I am assuming perhaps that gazebo is actually the default source, unless I am misunderstanding something. Thank you!

**Comment by ssicari** [comment]
> Hello, if the *-dev branch works for you I don't think that is the problem then but I still believe it is ardusub related. I have noticed that there are alot of plugins being ignored with mavros and I am not sure if they are supposed to be ignored or not. I copied over the terminal for the sim which I believe should include information on gazebo and ardusub. I am attaching a file too that has the qgroundcontrol terminal if you are curious. I tried to to set a flight plan so the bottom of the log files show the error messages when it fails to switch to guided mode. If you need any other logs just let me know, thank you! [Qgroundcontrol.txt](https://github.com/evan-palmer/blue/files/12305496/Qgroundcontrol.txt) [Gazebo_ArduSub.txt](https://github.com/evan-palmer/blue/files/12305498/Gazebo_ArduSub.txt)

from the Gazebo Localizer). You could also try slowing down/speeding up the Gazebo localizer.

I see the ROS2 node gazebo localizer and where you create it in the localization.launch.py file, but I have a question. I am struggling to find where the code is that could speed up or slow down the localizer, I found the localization.yaml file as well but it doesn't seem like that is exactly what I am looking for. Thank you!

**Comment by evan-palmer** [comment]
@ssicari I apologize for my inactivity! I have been finishing up experiments and paper submissions. I transferred ownership of the repo over to my lab's organization, so I recommend recloning. I saw your previous comment regarding unintalling blue and reinstalling it, and when you reclone, you will have to do that anyway

**Comment by evan-palmer** [comment]
> Thank you for the heads up on QGC. Regarding the transfer, are you done with the project, and going forward should I contact your lab? Thank you!

I will continue to be the primary maintainer of the project. I just transferred ownership to give the project a more permanent home for my paper

**Comment by ssicari** [comment]
> > Thank you for the heads up on QGC. Regarding the transfer, are you done with the project, and going forward should I contact your lab? Thank you!
> 
> I will continue to be the primary maintainer of the project. I just transferred ownership to give the project a more permanent home for my paper

Ah I see. I will be traveling for the next few weeks so I will have to try a reclone and see if that helps when I get home. Thank you!

**Comment by evan-palmer** [comment]
This has grown stale. I'm going to close this

**Pull request closed without merging**
